#include "PuzzleState.hpp"
#include <stdexcept>
#include <cmath>

#define HASH_PRIME 31 // prime factor for the polynomial hash

PuzzleState::PuzzleState() : PuzzleState(8) {} // calls the other constructor with N = 8

PuzzleState::PuzzleState(std::size_t n) {
    num_tiles = n;
    side_length = compute_side_length(n);
    size = n + 1;

    // goal state: tiles 1, 2, ..., N and the empty tile (0) as the last cell
    flat_matrix.resize(size);
    for (std::size_t i = 0; i < num_tiles; i++) {
        flat_matrix[i] = i + 1;
    }
    flat_matrix[size - 1] = 0;

    zero_pos = {side_length - 1, side_length - 1}; // bottom right corner
}

PuzzleState::PuzzleState(std::size_t n, const std::vector<std::uint8_t>& initial_board) {
    num_tiles = n;
    side_length = compute_side_length(n);
    size = n + 1;

    if (initial_board.size() != size) {
        throw std::invalid_argument("the board must have N + 1 cells");
    }

    flat_matrix = initial_board;

    // looking for the empty tile (0) only once, then zero_pos is updated by swap_tiles at every move
    for (std::size_t row = 0; row < side_length; row++) {
        for (std::size_t col = 0; col < side_length; col++) {
            if ((*this)(row, col) == 0) {
                zero_pos = {row, col};
                return;
            }
        }
    }

    throw std::invalid_argument("the board has no empty tile (0)");
}

std::size_t PuzzleState::compute_side_length(std::size_t n) {
    double root = std::sqrt(n + 1);

    // N + 1 is a perfect square only if its square root is an integer
    if (root != std::round(root)) {
        throw std::invalid_argument("N + 1 must be a perfect square (e.g. 8, 15, 24)");
    }

    return static_cast<std::size_t>(root);
}

void PuzzleState::swap_tiles(std::size_t r1, std::size_t c1, std::size_t r2, std::size_t c2) {
    std::uint8_t temp = (*this)(r1, c1);
    set_tile(r1, c1, (*this)(r2, c2));
    set_tile(r2, c2, temp);

    // if the empty tile was moved, update its cached position
    if ((*this)(r1, c1) == 0) {
        zero_pos = {r1, c1};
    } else if ((*this)(r2, c2) == 0) {
        zero_pos = {r2, c2};
    }
}

bool PuzzleState::operator==(const State& other) const {
    // other is a generic State, so we need to check if it's actually a PuzzleState
    const PuzzleState* other_puzzle = dynamic_cast<const PuzzleState*>(&other); // nullptr if other is not a PuzzleState
    if (other_puzzle == nullptr) {
        return false;
    }

    if (num_tiles != other_puzzle->num_tiles) {
        return false;
    }

    // same size: check every cell
    for (std::size_t i = 0; i < size; i++) {
        if (flat_matrix[i] != other_puzzle->flat_matrix[i]) {
            return false;
        }
    }

    return true;
}

std::size_t PuzzleState::hash() const {
    // polynomial hash: h = h * HASH_PRIME + tile, for every cell (with a prime, different boards give quite different hashes)
    std::size_t h = 0;
    for (std::size_t i = 0; i < size; i++) {
        h = h * HASH_PRIME + flat_matrix[i];
    }

    return h;
}

// this to_string() was fully generated by LLM.
std::string PuzzleState::to_string() const {
    std::string result;

    // width of the widest tile, so columns stay aligned even for e.g. the 15-puzzle
    std::size_t width = std::to_string(num_tiles).size();

    auto horizontal_rule = [&](const std::string& left, const std::string& mid, const std::string& right) {
        result += left;
        for (std::size_t col = 0; col < side_length; col++) {
            for (std::size_t k = 0; k < width + 2; k++) result += "─"; // ─
            result += (col + 1 < side_length ? mid : right);
        }
        result += "\n";
    };

    horizontal_rule("┌", "┬", "┐"); // ┌ ┬ ┐

    for (std::size_t row = 0; row < side_length; row++) {
        result += "│"; // │

        for (std::size_t col = 0; col < side_length; col++) {
            int tile = (*this)(row, col); // int, otherwise std::to_string would treat the uint8_t as a char

            result += " ";
            if (tile == 0) {
                result += std::string(width, ' ');
            } else {
                std::string number = std::to_string(tile);
                result += std::string(width - number.size(), ' ') + number; // right aligned
            }
            result += " │"; // │
        }

        result += "\n";

        if (row + 1 < side_length) {
            horizontal_rule("├", "┼", "┤"); // ├ ┼ ┤
        }
    }

    horizontal_rule("└", "┴", "┘"); // └ ┴ ┘

    return result;
}
